In [42]:
import pandas as pd

In [43]:
novels = pd.read_csv("../clean data/novel_data.csv", index_col=0)
novels.head()

,Writer Name,Novel Name,Genre,Final Word Count,Daily Average,Winner,Synopses,url,Novel Date
0,Nicaless,Novel: Lauren's Birthday,Genre: Young Adult,24229,807,0,\n<p></p>\n,http://nanowrimo.org/participants/nicaless/nov...,November 2015
1,Nicaless,Novel: A Mystery in the Kingdom of Aermon,Genre: Fantasy,50919,"1,697",1,\n<p>Hitoshi is appointed the youngest Judge a...,http://nanowrimo.org/participants/nicaless/nov...,November 2014
2,Rachel B. Moore,Novel: Finding Fortunato,Genre: Literary,50603,"1,686",1,\n<p>Sam and Anna Gold and their newly adoptiv...,http://nanowrimo.org/participants/rachel-b-moo...,November 2015
3,Rachel B. Moore,Novel: The Residency,Genre: Literary,50425,"1,680",1,\n<p>It's every writer's dream - an all-expens...,http://nanowrimo.org/participants/rachel-b-moo...,November 2014
4,Rachel B. Moore,Novel: The Jew From Fortunato,Genre: Literary Fiction,41447,"1,381",0,\n<p>20-something Andre Levinsky is a fish out...,http://nanowrimo.org/participants/rachel-b-moo...,November 2013

In [44]:
# clean novel name
novel_names = []
for n in novels['Novel Name']:
    novel_names.append(n.split("Novel: ")[1])

novels['Novel Name'] = novel_names
novels['Novel Name'].head()

0                     Lauren's Birthday
1    A Mystery in the Kingdom of Aermon
2                     Finding Fortunato
3                         The Residency
4                The Jew From Fortunato
Name: Novel Name, dtype: object

In [45]:
genre = []
for g in novels['Genre']:
    genre.append(g.split("Genre:")[1])

novels['Genre'] = genre
novels['Genre'].head()

0          Young Adult
1              Fantasy
2             Literary
3             Literary
4     Literary Fiction
Name: Genre, dtype: object

In [46]:
standard_genres = ['Adventure','Children\'s Fiction','Erotic','Fanfiction','Fantasy','Historical','Horror/Supernatural','Literary','Mainstream','Mystery','Personal','Religious/Spiritual','Romance','Satire/Humor','Science Fiction','Thriller/Suspense','Women\'s Fiction','Young Adult']

In [47]:
test = novels['Synopses'][1:10]
test

1    \n<p>Hitoshi is appointed the youngest Judge a...
2    \n<p>Sam and Anna Gold and their newly adoptiv...
3    \n<p>It's every writer's dream - an all-expens...
4    \n<p>20-something Andre Levinsky is a fish out...
5    \n<p>Andre Levinsky is a celebrated writer in ...
6    \n<p>On his last night in the US, Nicholas Cha...
7    \n<p>Abel works in the library, cataloging don...
8                                          \n<p></p>\n
9                                          \n<p></p>\n
Name: Synopses, dtype: object

In [55]:
has_synopses = []
num_words = []
num_unique = []
num_paragraphs = []
num_sentences = []
has_genre = []
standard_genre = []

from bs4 import BeautifulSoup

#for novel in test:
i = 0
for novel in novels['Synopses']:
    soup = BeautifulSoup(novel, 'html.parser')
    syn = soup.find_all("p")
    if syn[0].renderContents() == "":
        has_synopses.append(0)
        num_paragraphs.append(0)
    else:
        has_synopses.append(1)
        num_paragraphs.append(len(syn))
    num_sent = 0
    wc = 0
    uniques = 0
    for i in syn:
        line =  i.renderContents()
        num_sent = num_sent + line.count(".")
        wc = wc + len(line.split(" "))
        uniqueWords = []
        for j in line:
            if not j in uniqueWords:
                uniqueWords.append(i)
        uniques = uniques + len(uniqueWords)
    
    num_sentences.append(num_sent)
    num_words.append(wc)
    num_unique.append(uniques)

In [57]:
for genre in novels['Genre']:
    if genre == "":
        has_genre.append(0)
    else:
        has_genre.append(1)
    if genre in standard_genres:
        standard_genre.append(1)
    else:
        standard_genre.append(0)

In [58]:
print len(has_synopses)
print len(num_words)
print len(num_unique)
print len(num_paragraphs)
print len(num_sentences)
print len(has_genre)
print len(standard_genre)

2123
2123
2123
2123
2123
2123
2123

In [61]:
novel_features = pd.DataFrame(novels['Winner'])

In [63]:
novel_features['has_genre'] = has_genre
novel_features['standard_genre'] = standard_genre
novel_features['has_synopses'] = has_synopses
novel_features['num_words'] = num_words
novel_features['num_unique'] = num_unique
novel_features['num_paragraphs'] = num_paragraphs
novel_features['num_sentences'] = num_sentences

In [64]:
novel_features

,Winner,has_genre,standard_genre,has_synopses,num_words,num_unique,num_paragraphs,num_sentences
0,0,1,0,0,1,0,0,0
1,1,1,0,1,44,259,1,5
2,1,1,0,1,154,904,4,6
3,1,1,0,1,60,348,3,4
4,0,1,0,1,125,708,1,4
5,0,1,0,1,164,1006,1,8
6,1,1,0,1,177,1036,1,8
7,1,1,0,1,63,391,1,4
8,1,1,0,0,1,0,0,0
9,1,1,0,0,1,0,0,0
10,1,1,0,0,1,0,0,0
11,1,1,0,0,1,0,0,0
12,1,1,0,1,56,327,1,2
13,0,1,0,1,107,600,3,8
14,1,1,0,1,180,1039,5,8
15,1,1,0,1,45,240,2,2
16,1,1,0,1,48,280,1,4
17,1,1,0,1,18,96,1,1
18,1,1,0,1,22,123,2,2
19,0,1,0,1,8,71,1,3
20,0,1,0,1,24,121,1,1
21,1,1,0,1,28,174,1,2
22,0,1,0,1,33,185,2,2
23,0,1,0,1,26,132,1,1
24,1,1,0,1,18,117,1,0
25,1,1,0,1,16,90,1,1
26,0,1,0,1,53,304,2,2
27,0,1,0,1,51,285,2,2
28,0,1,0,1,87,502,1,5
29,0,1,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...
2093,1,1,0,1,23,119,1,2
2094,1,1,0,1,39,259,1,2
2095,1,1,0,1,11,68,1,1
2096,1,1,0,1,38,212,1,2
2097,1,1,0,1,24,142,1,1
2098,1,1,0,1,27,148,1,1
2099,1,1,0,1,41,237,1,4
2100,1,1,0,1,36,217,1,2
2101,1,1,0,1,23,131,1,2
2102,0,1,0,0,1,0,0,0
2103,1,1,0,1,239,1446,5,6
2104,0,1,0,1,156,891,1,13
2105,1,1,0,1,18,93,1,1
2106,1,1,0,1,59,346,1,2
2107,1,1,0,1,30,156,1,1
2108,1,1,0,1,7,26,1,3
2109,1,1,0,1,1,7,1,0
2110,0,1,0,1,43,233,1,3
2111,0,1,0,0,1,0,0,0
2112,0,1,0,1,60,330,1,4
2113,1,1,0,1,280,1681,7,11
2114,1,1,0,1,14,86,3,2
2115,1,0,0,1,46,242,1,4
2116,1,1,0,0,1,0,0,0
2117,1,1,0,1,33,199,1,1
2118,1,1,0,0,1,0,0,0
2119,1,1,0,1,147,872,2,8
2120,1,1,0,1,20,118,1,1
2121,1,1,0,1,21,116,3,3
2122,1,1,0,0,1,0,0,0

In [65]:
novel_features.to_csv("novel_features.csv")